# -*- coding: utf-8 -*-
"""EDA_MALL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1enenguRrlXynE9vFok6ucfm5vSdI3sX1

## EDA done using manual methods
"""

# Mount Drive
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
# Load the dataset
df = pd.read_csv(r"/content/drive/MyDrive/Mall.csv")
df.head()

# Step 1: Identify and handle missing values
print("Missing values before handling:")
print(df.isnull().sum())

# Step 2: Remove duplicate rows
print(f"\nNumber of rows before removing duplicates: {len(df)}")
df = df.drop_duplicates()
print(f"Number of rows after removing duplicates: {len(df)}")

# Shape of the dataset
df_shape = df.shape
print(f"Shape of the dataset: {df_shape}")

# Change the gender in numeric
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 0})

df.sample(2)

df.columns

df.info()

# Rename column
df = df.rename(columns={'Annual Income (k$)': 'Annual_Income'})

# Rename the column
df = df.rename(columns={'Spending Score (1-100)': 'Spending_Score'})

df.describe()

import seaborn as sns
sns.pairplot(df)

# column chart for gender count
sns.countplot(x='Gender', data=df, palette='viridis')

# Correlation matrix
corr_matrix = df.corr()
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')

"""## Performed EDA using advanced ydata-profiling library"""

pip install ydata-profiling

from ydata_profiling import ProfileReport
profile = ProfileReport(df, title="Profiling Report")
profile.to_file("Result.html")

from google.colab import files

# Saves a html file
files.download('/content/Result.html')